[package]
name = "matrix"
version = "1.0.0"
edition = "2021"

[dependencies]
macroquad = "0.3.15"
quad-rand = "0.2.1"
instant = "0.1.12"
csscolorparser = "0.5.0"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.10.0"

[build-dependencies]
winres = "0.1"