#------------------------- 凤凰点阵体 -------------------------
# #characters = "アイウエオカキクケコサシスセソタチツテトナニヌネハヒフヘホマミムメモヤユヨラリルレワヰヱヲン・"
# characters = "01"
# font = "1"
# font_size = 16
# spaceing = 0
#-------------------------------------------------------------

#------------------------- 甲骨文配置 -------------------------
characters = "㐁㐭㓞㕚㕣㚔㚤㛸㝛㝵㠯㦰㦵㨉㪔㪿㫃㯟㯥㱃㱿㲋㳄㳑㹞㺇㻎㽙㿝䇂䊤䍜䍩䎽䖵䡴䢔䮯䲨䵼一丁丂七万三上下不丏丐丑且丕丘丙丞並丩中丮丯丰丹主丽乂乃乇之乍乎乘乙九乞乳亅事二于云五井亘亙亞亟亡亢亥亦亨享京亯人仄今介从令以任企伇伊伏伐休伯何余作使侃來侖侚供侯侵係俘保俞倉倗偁備傳僤允元兄兆先光克兌免兒兔兕入兩八公六兮共兵其具典兹冉册再冎冒冓冕冗冟冠冡冬几凡出函刀刁刃分刈刖刜初删別利别刵刺則剌剛割劓力劦助勞勹勿匄匆匕化北匚匝匿區十千卅升午卌卒協南卜占卣卩卯印卲即卿厀厃厚原厥厷去叀叁參又及友反叔取受叜叟叡口古叩召可史右司各合吉同名吏向吕君启吹呂告周呪呼命咎咒咸品員唐唬唯商啓啚啟喁喜喦喪單嗅嗇嘉噎嚨嚴四囟因囧困固囿圉國圍圓土在圭坎坐城域埶執堇堯塞墉壇壬壴壺夆夌复夏夒夕夗夙多夜夢大夨天夫央夷夸夾奏契奔奚奠奡女奻好如妃妊妌妍妝妣妥妸妹妻妾姃姓委姛姜姝姪姫姬姸姼娕娘娠娥娩娶婡婢婤婦婭媚媟媳嫀嬂嬉子孕孚孛季孫孰學孽宀宁它宅守安宋宓宕宗官定宛宜宣室宧宫宬宮宰害宵家宷宿寅寇寍寐寒寢寤寧審寮寶尃射將專尊尋尌對小少尗尚尞尨就尸尹尻尾尿屎履屮屯屰山岳嶲巂川州巡巢工左巫己已巳巴巸帀市帚帛帝帥師帶帽干年并幼幽庇床庚度庭庶康庸廄廌廩延建廼廾廿弋弓弔引弗弘弜弟弦強彔彖彗彘彝彡彭彶往征律後徏徒得徝從御復微徵徹心必念恆恒恙息悤惠慶懋懸戈戉戊戌戍戎成我戒戔戕或戚戠截戴户才扶承抆抑折抱抿拇拯拱振捪捷掃授掔探掫援搔摣撣擇擒攣攴攵攸改敎敏敖敗教敝敢散敦文斗斝斤斧新方斿旁旅旋族旐旡既日旦旨旬旾昃昌明昏易昔昜星春昱昷晉晝晨晴晵晶智暈暮暴曰曲更曹曼曾替朁會月有朊朋服朕朙望朝朢木未朮朱朿杉杕杞束東杳杵析林枚枹枼柏柲柳栽桐桑梁棄棋棗棘森椎楚極榆槁樁樂樴樹橐檀櫅櫑櫓櫛櫟欠次欶止正此步武歲歷歸歺死殊殞殟殲殷殺毋母每毓比氏民氒气水永求汏汜汝汫沁沈沉沓沖沙沚沝沬河泉泊注洀洗洚洛洱洲洹派涂涉涎涵涷淮深淵温湄湡溢溫溼溽滅滳漁潢潦潾澅澫濘濞濤濩濼瀑瀕瀧瀼灂火災灾炋炎為烈烕焚焛無焱熊熟熹燀燎燕燮爪爭爯爰爲爵父爻爽爾爿牀牆牛牝牟牡牢牧物牽犬狐狩狼狽猱猶猷獏獲獸獻率玉王玨珏現琮瑟璞璧瓚甗甘生用甫田由甲申男甹甾畀畋畏畐畜畢畫畯異疇疋疌疐疑疒疾痍癭癸癹登發白百皆皇皮皿盂益盍盟盡監盤盧目直相盾省眉眔眚眴眾睫瞽矢知石砅砋硪磬示祀祈祏祐祖祗祝神祠祫祭祼禘禦禫禱禽禾秀秉秋秜秦秫稼稽穆穗穫突窺立竝竟童競竹竽笮箕箙簋簟米粦粼糞索紳終絲網編縣缶罈网罔罙罝罩置罷羅羆羈羊羋羌美羔羞義羲羴翌習翟翦翼老耋耑耤耳聖聞聯聰聲聶聽聾聿肆肇肈肉肘肩肱育胄背胵能腋腰腹膏膝膺臀臣臤臧臨自臬臭至臺臽臾舂興舊舌舍舝舞舟般良艱艾艿芒芟芻苑苞若茍茨莫莽萅萈萑萬葉葬蒙蒿蓑蔑蔖蔡蕘薛薦薪藝虍虎虐虒虘虞虣虤虫虹虺蛇蛛蜀蝠融蠃蠢蠱血衆行衍衛衣衰袁裘襄襲西要覃見視觀角解觴言訊訢誅谷豆豊豐豕豖豚象豪豭豹貔貝貞貪責買賈賓賞赤走趾踊踰躋身車輦轡辛辟辭辰農达迅迺追退逆逋逐通速逢進逴逸逾遘遝遠遣遭遲遼還邇邊邍邑邕郊郭鄉鄙鄰酉酌配酒酓醜采釋重量鉞錫鍥鏑鑄鑊鑿長門閤闔阜阱防降陟陮陰陶陷陸陽隹隻雀集雇雈雉雋雍雔雚雛雝雞雥雨雩雪雲雷雹電震霋霍霖霝霰霸霾靃非面革鞭韋頁項須頤頮頻顛風食飲飽餗饈饗首馘香馬駁駛駜騩騽驅驑驟驪骨高髟髦髭鬥鬮鬯鬱鬲鬳鬼鬽魚魯鯀鳥鳧鳳鳴鳶鴻鷄鹵鹿麇麋麐麓麗麟麥黃黍黑黹鼄鼉鼎鼓鼜鼠鼻齊齒齲龍龐龔龜龠龢"
font = "3"
font_size = 26
spaceing = 3
#-------------------------------------------------------------

#------------------------- 小篆体配置 -------------------------
# characters = "一乙九了七八厂儿二几力人入十又乃丁卜刀三上下与也之于千及大干工己口山才土小子久丸丈勺刃凡亡叉川寸弓巾女尸士夕中不公六切元五今化什反天引少比斗方火毛片气日手水王文心月支分丰乏丹予丑勿允互井云匹凶介仇仆仁仍升午友屯夫巨尺巴幻尤孔父斤木牛欠犬氏瓦牙止爪且世主包北加出代半去平布市叫可史只它四外本民必正白立目生石示用乎丘丙占刊兄印功令付仔失央巧左句古司台右召宁奴犯尼扔汁圣幼冬孕末未旦永甘瓜禾矛母皮甲申田穴玉"
# # 字体 "1"->凤凰点阵体 "2"->小篆 "3"->甲骨文 "字体文件名.ttf"->自定义ttf文件
# font = "2"
# # 字号
# font_size=22
# # 字符上下间距
# spaceing = 3
#-------------------------------------------------------------

# 字符突变率 0不突变
mutation_rate = 0.001

# 闪光颜色
light_color="#fff"
# 闪光消失速度（alpha透明度255递减)
light_speed=200

# 消失速度 （alpha透明度255递减)
fade_speed=10

# 雨帘前进延时(毫秒)
step_delay=60

# 文字颜色
color="rgb(0, 255, 70)"

# 背景色
background="#000"

# 全屏模式
fullscreen=false

# 窗口大小 计算方式:
#    屏幕实际分辨率=2880x1800 缩放=200% 那么窗口宽=2880/2=1440, 高=1800/2=900
#    屏幕实际分辨率=1920x1080 缩放=100% 那么窗口宽=1920, 高=1080
window_width=900
window_height=600

# 帧延时 1000/50=20帧 延时越小，CPU占用率越高
frame_delay = 50